CREATE TABLE IF NOT EXISTS `wp_wx_userlist` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`p_name`  varchar(50) NOT NULL  DEFAULT 'none' COMMENT '用户姓名',
`c_name`  varchar(50) NOT NULL  COMMENT '孩子姓名',
`phone`  varchar(50) NOT NULL  COMMENT '用户手机号',
`classid`  varchar(50) NOT NULL  DEFAULT 'None' COMMENT '班级编号',
`relation`  varchar(50) NOT NULL  COMMENT '绑定关系',
`openid`  varchar(50) NOT NULL  COMMENT 'OpenID',
`status`  tinyint(1) NULL  DEFAULT 1 COMMENT '用户状态',
`userid`  varchar(50) NOT NULL  DEFAULT 'none' COMMENT '考勤编号',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_wx_userlist` (`id`,`p_name`,`c_name`,`phone`,`classid`,`relation`,`openid`,`status`,`userid`) VALUES ('13','张德','王者','18829272629','abc123','M-m','o0N6jtwUl-JZaGFWXyDIVpJ1NKOc','2','123456');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('wx_userlist','微信用户列表','0','','1','{"1":["p_name","c_name","phone","relation","openid","status","userid","classid"]}','1:基础','','','','','p_name:用户姓名\r\nphone:手机号\r\nc_name:孩子姓名\r\nuserid:考勤编号\r\nrelation:绑定关系\r\nclassid:班级编号\r\nopenid:OpenID\r\nid:操作:[DELETE]|删除\r\n','10','','','1437533066','1437642902','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('p_name','用户姓名','varchar(50) NOT NULL','string','none','','1','','0','0','1','1437533198','1437533198','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('c_name','孩子姓名','varchar(50) NOT NULL','string','','','1','','0','0','1','1437533256','1437533256','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','用户手机号','varchar(50) NOT NULL','string','','','1','','0','0','1','1437533317','1437533317','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('classid','班级编号','varchar(50) NOT NULL','string','None','','1','','0','0','1','1437637249','1437533364','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('relation','绑定关系','varchar(50) NOT NULL','string','','','1','','0','0','1','1437533424','1437533424','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','OpenID','varchar(50) NOT NULL','string','','','1','','0','0','1','1437533476','1437533476','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','用户状态','tinyint(1) NULL','select','1','','1','0:未关注\r\n1:已关注\r\n2:已绑定\r\n3:管理员','0','0','1','1437535322','1437535322','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('userid','考勤编号','varchar(50) NOT NULL','string','none','','1','','0','0','1','1437535424','1437535424','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;